import { Geist, Geist_Mono } from 'next/font/google'
import QueryProvider from '@/providers/QueryProvider'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	viewport:
		'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<QueryProvider>{children}</QueryProvider>
			</body>
		</html>
	)
}
