/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
	const { nodes } = useGLTF('/comp2.glb')
	const instances = useMemo(
		() => ({
			Object: nodes.Object_10,
			Object1: nodes.Object_11,
			Object2: nodes.Object_12,
			Object3: nodes.Object_13,
			Object4: nodes.Object_2,
			Object5: nodes.Object_3,
			Object6: nodes.Object_4,
			Object7: nodes.Object_5,
			Object8: nodes.Object_6,
			Object9: nodes.Object_7,
			Object10: nodes.Object_8,
			Object11: nodes.Object_9,
		}),
		[nodes]
	)
	return (
		<Merged meshes={instances} {...props}>
			{(instances) => (
				<context.Provider value={instances} children={children} />
			)}
		</Merged>
	)
}

export function Model(props) {
	const instances = useContext(context)
	return (
		<group {...props} dispose={null}>
			<group
				// position={[-0.05, -0.01, -0.01]}
				position={[0, -0.45, 4.2]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.4}
			>
				<instances.Object />
				<instances.Object1 />
				<instances.Object2 />
				<instances.Object3 />
				<instances.Object4 />
				<instances.Object5 />
				<instances.Object6 />
				<instances.Object7 />
				<instances.Object8 />
				<instances.Object9 />
				<instances.Object10 />
				<instances.Object11 />
			</group>
		</group>
	)
}

useGLTF.preload('/comp2.glb')
